# Joke Joke starting items
- type: startingGear
  id: KoboldPirateBartenderGear
  equipment:
    head: ClothingHeadBandRed
    ears: ClothingHeadsetPirate
    jumpsuit: ClothingUniformJumpsuitPirateAntag
    id: JokeJokeIDCard
  inhand:
  - WeaponPistolFlintlock
