- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 5h
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
  # id: ChemistryPDA # Moffstation - PDA loadouts
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
  # eyes: ClothingEyesGlassesChemical # Moffstation - Eyepatches!
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ChemistChameleonOutfit
  job: Chemist
  equipment:
    head: ClothingHeadHatBeretMedic
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabChem
    gloves: ClothingHandsGlovesLatex
