- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  # Moffstation - Start - Change role timers
  #requirements:
  #- !type:DepartmentTimeRequirement
  #  department: Medical
  #  time: 2.5h
  # Moffstation - End
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - External # Moffstation - Give paramedics externals
  extendedAccess:
  - Chemistry

- type: startingGear
  id: ParamedicGear
  equipment:
#    id: ParamedicPDA # Moffstation - PDA loadouts
    ears: ClothingHeadsetMedical

- type: chameleonOutfit
  id: ParamedicChameleonOutfit
  job: Paramedic
  equipment:
    head: ClothingHeadHatParamedicsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatParamedicWB
    gloves: ClothingHandsGlovesLatex
