- type: bluebenchResearch
  id: BasicSecurityResearch
  name: Cuff'n'Dagger
  description: Sometimes, war is a question, and the answer is yes.
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  tagRequirements:
    Arrow:
      amount: 2
      defaultPrototype: ArrowImprovisedRock
  stackRequirements:
    Cable: 5
  outputRecipes:
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties
  - CombatKnife

- type: bluebenchResearch
  id: CommonSecurityResearch
  name: Non-Lethal Weaponry
  description: Pick up that can.
  requiredResearch:
  - BasicSecurityResearch
  icon:
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    state: stunbaton_off
  stackRequirements:
    Steel: 15
    Plastic: 5
  outputRecipes:
  - Flash
  - Stunbaton
  - RiotShield
  - WeaponDisabler
