- type: antag
  id: PirateCrew
  name: roles-antag-pirate-crew-name
  antagonist: true
  setPreference: true
  objective: roles-antag-pirate-crew-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ Pirates ]

- type: antag
  id: PirateCaptain
  name: roles-antag-pirate-captain-name
  antagonist: true
  setPreference: true
  objective: roles-antag-pirate-captain-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ Pirates ]

- type: startingGear
  id: PirateGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirateAntag
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket2: PinpointerPirate
    ears: ClothingHeadsetPirate

- type: startingGear
  id: PirateCaptainGear
  parent: PirateGear
  equipment:
    neck: ClothingNeckCloakPirateCap
    id: PirateCaptainPDA
  storage:
    back:
    - EnergyCutlass

- type: startingGear
  id: FlyingDutchmanGear
  equipment:
    pocket2: Cutlass
