- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  # Moffstation - Start - Change role timers
  #requirements:
  #- !type:RoleTimeRequirement
  #  role: JobSecurityOfficer
  #  time: 5h
  # Moffstation - End
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Detective
  - Cryogenics
  - External
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
  # eyes: ClothingEyesGlassesSecurity # Moffstation - Eyepatches!
  # id: DetectivePDA # Moffstation - PDA loadouts
    ears: ClothingHeadsetSecurity
    #belt: ClothingBeltHolsterFilled # Moffstation - (Nox Loadout Improvements) - They get to choose a belt in loadouts instead.
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
    # Moffstation - Begin - (Give detective tape recording equipment)
    - TapeRecorder
    - CassetteTape
    - CassetteTape
    # Moffstation - End

- type: chameleonOutfit
  id: DetectiveChameleonOutfit
  job: Detective
  hasMindShield: true
  equipment:
    head: ClothingHeadHatFedoraBrown
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckTieDet
    gloves: ClothingHandsGlovesForensic
