- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    # Moffstation - Start - Change role timers
    - !type:OverallPlaytimeRequirement
      time: 20h
    # Moffstation - End
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: WardenGear
  equipment:
  # eyes: ClothingEyesGlassesSecurity # Moffstation - Eyepatches!
  # id: WardenPDA # Moffstation - PDA loadouts
    ears: ClothingHeadsetAltSecurity # Moffstation - (Give Warden Command Comms)
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
