# ID

# Head

# Mask

# Neck

# Jumpsuit

# Back

# Belt

# Outer Clothing
- type: loadout
  id: HeadofSecurityCarapace
  equipment:
    outerClothing: ClothingOuterArmorHoSCarapace

# Gloves

# Shoes

# Eyewear
