- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  # Moffstation - Start - Change role timers
  #requirements:
  #- !type:DepartmentTimeRequirement
  #  department: Civilian
  #  time: 0.5h
  # Moffstation - End
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    shoes: ClothingShoesColorBlack
#    id: ServiceWorkerPDA # Moffstation - PDA loadouts
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ServiceWorkerChameleonOutfit
  job: ServiceWorker
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterVest
    gloves: ClothingHandsGlovesColorBlack
