- type: startingGear
  id: PirateGearUpstream  # Moffstation - Using our namespace
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    back: ClothingBackpackSatchelLeather
    head: ClothingHeadBandBlack
    shoes: ClothingShoesBootsLaceup
    id: PiratePDA
    belt: ClothingBeltUtility
    pocket1: AppraisalTool

- type: startingGear
  id: PirateCaptainGearUpstream  # Moffstation - Using our namespace
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirate
    pocket2: EnergyCutlass
    outerClothing: ClothingOuterCoatPirate

- type: startingGear
  id: PirateFirstmateGearUpstream  # Moffstation - Using our namespace
  parent: PirateGear
  equipment:
    head: ClothingHeadHatPirateTricord
    outerClothing: ClothingOuterCoatGentle

- type: chameleonOutfit
  id: PirateChameleonOutfit
  name: roles-antag-pirate-name
  icon: "JobIconPirate"
  startingGear: PirateFirstmateGearUpstream # Moffstation - Using our namespace
  equipment:
    eyes: ClothingEyesEyepatch
    ears: ClothingHeadsetFreelance
    mask: ClothingMaskNeckGaiter
    neck: ClothingNeckBling
    gloves: ClothingHandsGlovesColorLightBrown
    outerClothing: ClothingOuterCoatPirate

